export enum BaksDAOErrors {
  CollateralTokenZeroDecimals = "BaksDAOCollateralTokenZeroDecimals",
  CollateralTokenTooLargeDecimals = "BaksDAOCollateralTokenTooLargeDecimals",
  CollateralTokenAlreadyListed = "BaksDAOCollateralTokenAlreadyListed",
  CollateralTokenNotListed = "BaksDAOCollateralTokenNotListed",
  TokenNotAllowedAsCollateral = "BaksDAOTokenNotAllowedAsCollateral",
  InitialLoanToValueRatioTooHigh = "BaksDAOInitialLoanToValueRatioTooHigh",
  FeesDontSumUpToOne = "BaksDAOFeesDontSumUpToOne",
  InactiveLoan = "BaksDAOInactiveLoan",
  LoanNotSubjectToLiquidation = "BaksDAOLoanNotSubjectToLiquidation",
  LoanIsSubjectToLiquidation = "BaksDAOLoanIsSubjectToLiquidation",
  BorrowZeroAmount = "BaksDAOBorrowZeroAmount",
  DepositZeroAmount = "BaksDAODepositZeroAmount",
  RepayZeroAmount = "BaksDAORepayZeroAmount",
  NoNeedToRebalance = "BaksDAONoNeedToRebalance",
  StabilizationFundOutOfFunds = "BaksDAOStabilizationFundOutOfFunds",
  TokenNotAllowedToBeSalvaged = "BaksDAOTokenNotAllowedToBeSalvaged",
  PlainNativeCurrencyTransferNotAllowed = "BaksDAOPlainNativeCurrencyTransferNotAllowed",
}
