/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  DevelopmentFund,
  DevelopmentFundInterface,
} from "../DevelopmentFund";

const _abi = [
  {
    inputs: [],
    name: "ContractAlreadyInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "GovernedCantGoverItself",
    type: "error",
  },
  {
    inputs: [],
    name: "GovernedGovernorZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "GovernedOnlyGovernorAllowedToCall",
    type: "error",
  },
  {
    inputs: [],
    name: "GovernedOnlyPendingGovernorAllowedToCall",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "governor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newGovernor",
        type: "address",
      },
    ],
    name: "GovernanceTransited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "governor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newGovernor",
        type: "address",
      },
    ],
    name: "PendingGovernanceTransition",
    type: "event",
  },
  {
    inputs: [],
    name: "acceptGovernance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "governor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingGovernor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newGovernor",
        type: "address",
      },
      {
        internalType: "bool",
        name: "force",
        type: "bool",
      },
    ],
    name: "transitGovernance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506103a8806100206000396000f3fe608060405234801561001057600080fd5b50600436106100675760003560e01c80638129fc1c116100505780638129fc1c146100ab578063ddc12526146100b3578063e3056a34146100c657600080fd5b80630c340a241461006c578063238efcbc146100a1575b600080fd5b600054610085906201000090046001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b6100a96100d9565b005b6100a961016e565b6100a96100c1366004610351565b6101e0565b600154610085906001600160a01b031681565b6001546001600160a01b031633146101045760405163aec80d4b60e01b815260040160405180910390fd5b60015460008054620100006001600160a01b0393841681810275ffffffffffffffffffffffffffffffffffffffff00001990931692909217808455604051929491900416917f564590b81987d147246f63910a8e1ee4eb09c4d64cc75ee975a8ffedfcc2210e91a3565b60005460ff161580156101885750600054610100900460ff165b156101a657604051631ee1e30360e21b815260040160405180910390fd5b60005460ff161580156101c3576000805461ffff19166101011790555b6101cc336102ea565b80156101dd576000805460ff191690555b50565b6000546201000090046001600160a01b03163314610211576040516305e7700560e51b815260040160405180910390fd5b6001600160a01b0382166102385760405163604b48b960e11b815260040160405180910390fd5b6001600160a01b038216301415610262576040516306b3e95d60e21b815260040160405180910390fd5b600180547fffffffffffffffffffffffff0000000000000000000000000000000000000000166001600160a01b038416179055806102dd57600080546040516001600160a01b03808616936201000090930416917fc606c9af1451cadeb333f6ff7b24a5540974f4e800bac274fa7fff9edc305cb191a35050565b6102e6826102ea565b5050565b6000805475ffffffffffffffffffffffffffffffffffffffff00001916620100006001600160a01b0384811682810293909317808555604051939492900416917f564590b81987d147246f63910a8e1ee4eb09c4d64cc75ee975a8ffedfcc2210e9190a350565b6000806040838503121561036457600080fd5b82356001600160a01b038116811461037b57600080fd5b91506020830135801515811461039057600080fd5b80915050925092905056fea164736f6c634300080a000a";

type DevelopmentFundConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DevelopmentFundConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DevelopmentFund__factory extends ContractFactory {
  constructor(...args: DevelopmentFundConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DevelopmentFund> {
    return super.deploy(overrides || {}) as Promise<DevelopmentFund>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DevelopmentFund {
    return super.attach(address) as DevelopmentFund;
  }
  connect(signer: Signer): DevelopmentFund__factory {
    return super.connect(signer) as DevelopmentFund__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DevelopmentFundInterface {
    return new utils.Interface(_abi) as DevelopmentFundInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DevelopmentFund {
    return new Contract(address, _abi, signerOrProvider) as DevelopmentFund;
  }
}
